baseURL: "https://my.j91.asia/"
title: Javsubs91
paginate: 16
theme: coyote
enableRobotsTXT: true

# params:
#   profile:
#     enabled: true
#     name: John Doe
#     description: I've got something to tell you now, Walkman
#   social:
#     - name: github
#       url: https://j4ev.pages.dev

menu:
  main:
    - identifier: search
      name: Search
      url: search/
outputs:
    home:
        - HTML
        - JSON

taxonomies:
  tag: "tags"
  category: "maker"
  series: "actress"

related:
  includeNewer: true
  indices:
  - name: title
    weight: 30
  - name: actress
    weight: 30
  - name: maker
    weight: 30
  - name: description
    weight: 30
  - name: tags
    weight: 30
  - name: date
    weight: 10
  threshold: 80
  toLower: false
